services:
  web:
    # On prend la racine du projet comme contexte pour copier aussi 'scripts' et 'web'
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/dumps:/data/dumps
      - ./data/filestore:/data/filestore
      - ./data/manifest.json:/data/manifest.json
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: